use super::CliSSLConfig;
use super::CliConnInfo;
use super::ClusterManagerCommand;
use super::consts;

pub struct CliConfig {
    pub conn_info: CliConnInfo,
    pub host_socket: String,
    pub tls: i32,
    pub ssl_config: CliSSLConfig,
    pub repeat: i64,
    pub interval: i64,
    pub db_num: i32,
    pub interactive: i32,
    pub shutdown: i32,
    pub monitor_mode: i32,
    pub pub_sub_mode: i32,
    pub blocking_state_aborted: i32,
    pub latency_mode: i32,
    pub latency_dist_mode: i32,
    pub latency_history: i32,
    pub lru_test_mode: i32,
    pub lru_test_sample_size: i64,
    pub cluster_mode: i32,
    pub cluster_reissue_command: i32,
    pub cluster_send_asking: i32,
    pub slave_mode: i32,
    pub pipe_mode: i32,
    pub pipe_timeout: i32,
    pub get_rdb_mode: i32,
    pub get_functions_rdb_mode: i32,
    pub stat_mode: i32,
    pub scan_mode: i32,
    pub intrinsic_latency_mode: i32,
    pub intrinsic_latency_duration: i32,
    pub pattern: String,
    pub rdb_filename: String,
    pub big_keys: i32,
    pub mem_keys: i32,
    pub mem_keys_samples: u32,
    pub hot_keys: i32,
    pub stdin_last_arg: i32,
    pub stdin_tag_arg: i32,
    pub stdin_tag_name: String,
    pub ask_pass: i32,
    pub quoted_input: i32,
    pub output: i32,
    pub push_output: i32,
    pub mb_delim: String,
    pub cmd_delim: String,
    pub prompt: [char; 128],
    pub eval: String,
    pub eval_ldb: i32,
    pub eval_ldb_sync: i32,
    pub eval_ldb_end: i32,
    pub enable_ldb_on_eval: i32,
    pub last_cmd_type: i32,
    pub verbose: i32,
    pub set_errcode: i32,
    pub cluster_manager_command: ClusterManagerCommand,
    pub no_auth_warning: i32,
    pub resp2: i32,
    pub resp3: i32,
    pub in_multi: i32,
    pub pre_multi_db_num: i32,
}

impl CliConfig {
    pub fn new() -> CliConfig {
        CliConfig {
            conn_info: CliConnInfo::new(),
            host_socket: "".to_string(),
            tls: 0,
            ssl_config: CliSSLConfig::new(),
            repeat: 1,
            interval: 0,
            db_num: 0,
            interactive: 0,
            shutdown: 0,
            monitor_mode: 0,
            pub_sub_mode: 0,
            blocking_state_aborted: 0,
            latency_mode: 0,
            latency_dist_mode: 0,
            latency_history: 0,
            lru_test_mode: 0,
            lru_test_sample_size: 0,
            cluster_mode: 0,
            cluster_reissue_command: 0,
            cluster_send_asking: 0,
            slave_mode: 0,
            pipe_mode: 0,
            pipe_timeout: consts::REDIS_CLI_DEFAULT_PIPE_TIMEOUT,
            get_rdb_mode: 0,
            get_functions_rdb_mode: 0,
            stat_mode: 0,
            scan_mode: 0,
            intrinsic_latency_mode: 0,
            intrinsic_latency_duration: 0,
            pattern: "".to_string(),
            rdb_filename: "".to_string(),
            big_keys: 0,
            mem_keys: 0,
            mem_keys_samples: 0,
            hot_keys: 0,
            stdin_last_arg: 0,
            stdin_tag_arg: 0,
            stdin_tag_name: "".to_string(),
            ask_pass: 0,
            quoted_input: 0,
            output: consts::OUTPUT_STANDARD,
            push_output: 1,
            mb_delim: "\n".to_string(),
            cmd_delim: "\n".to_string(),
            prompt: [' '; 128],
            eval: "".to_string(),
            eval_ldb: 0,
            eval_ldb_sync: 0,
            eval_ldb_end: 0,
            enable_ldb_on_eval: 0,
            last_cmd_type: -1,
            verbose: 0,
            set_errcode: 0,
            cluster_manager_command: ClusterManagerCommand::new(),
            no_auth_warning: 0,
            resp2: 0,
            resp3: 0,
            in_multi: 0,
            pre_multi_db_num: 0,
        }
    }
}